# my-blog/sonata.toml
title = "sonata" # The title of the site.

# Default values of the optional fields.
# --------------------------------------
base = "/"
ximage = ""             # The image used in twitter preview.
favicon = "favicon.svg" # The path to the favicon.
out = "out"             # The path to the output directory.
posts = "posts"         # The path to the posts.
public = "public"       # The path to the public directory.
templates = "templates" # The path to the templates.
theme = "theme.css"     # The path to the theme.css
